server:
  port: 9001

spring:
  application:
    name: eureka-server
  security:
    user:
      name: jack
      password: jack
eureka:
  client:
    serviceUrl:
      defaultZone: http://jack:jack@localhost:9001/eureka
    fetch-registry: false
    register-with-eureka: false