server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://jack:jack@localhost:9001/eureka
spring:
  application:
    name: eureka-consumer
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

